// Generated by CoffeeScript 1.12.7
var Circle, THICKNESS;

THICKNESS = 0.05;

Circle = (function() {
  function Circle(col, radius, circles) {
    var c, count, i, len;
    this.col = col;
    this.radius = radius;
    count = 1;
    while (count > 0) {
      this.x = random(width);
      this.y = random(height);
      count = 0;
      for (i = 0, len = circles.length; i < len; i++) {
        c = circles[i];
        if (dist(c.x, c.y, this.x, this.y) < this.radius * 0.4) {
          count += 1;
        }
      }
    }
    this.marked = false;
  }

  Circle.prototype.draw = function() {
    if (game.ring) {
      fill(this.col);
      noStroke();
      sw(THICKNESS * this.radius);
      circle(this.x, this.y, (1 - THICKNESS / 2) * this.radius);
      noFill();
      stroke(255, 255, 255, 225);
      sw(THICKNESS * this.radius);
      return circle(this.x, this.y, this.radius);
    } else {
      fill(this.col);
      noStroke();
      sw(THICKNESS * this.radius);
      return circle(this.x, this.y, (1 + THICKNESS / 2) * this.radius);
    }
  };

  Circle.prototype.within = function(x, y) {
    return dist(this.x, this.y, x, y) < (1 + THICKNESS / 2) * this.radius;
  };

  return Circle;

})();
